import type { CelestialBodyId } from './planets'

export interface CelestialFact {
  id: CelestialBodyId
  name: string
  nameTr: string
  emoji: string
  typeTr: string // 'Karasal Gezegen' | 'Gaz Devi' | 'Buz Devi' | 'Cüce Gezegen' | 'Yıldız' | 'Doğal Uydu'
  radiusKm: string
  distFromSunAu: string
  rotationPeriod: string
  orbitPeriod: string
  moonsCount: string
  atmosphere: string
  funFactTr: string
}

export const CELESTIAL_FACTS: Record<CelestialBodyId, CelestialFact> = {
  sun: {
    id: 'sun',
    name: 'Sun',
    nameTr: 'Güneş',
    emoji: '☀️',
    typeTr: 'Sarı Cüce Yıldız (G2V)',
    radiusKm: '696,340 km (109× Dünya)',
    distFromSunAu: '0 AU (Merkez)',
    rotationPeriod: '25 - 35 gün',
    orbitPeriod: '230 milyon yıl (Samanyolu etrafında)',
    moonsCount: '8 Gezegen + Cüce Gezegenler',
    atmosphere: 'Hidrojen (%73), Helyum (%25)',
    funFactTr: 'Güneş Sistemimizin toplam kütlesinin %99.86\'sını tek başına oluşturur.',
  },
  earth: {
    id: 'earth',
    name: 'Earth',
    nameTr: 'Dünya',
    emoji: '🌍',
    typeTr: 'Karasal Gezegen',
    radiusKm: '6,371 km',
    distFromSunAu: '1.00 AU (149.6 milyon km)',
    rotationPeriod: '23 saat 56 dk',
    orbitPeriod: '365.25 gün',
    moonsCount: '1 (Ay)',
    atmosphere: 'Azot (%78), Oksijen (%21), Argon (%0.9)',
    funFactTr: 'Yüzeyinde sıvı halde su barındıran ve yaşamın bilindiği tek gök cismidir.',
  },
  moon: {
    id: 'moon',
    name: 'Moon',
    nameTr: 'Ay',
    emoji: '🌕',
    typeTr: 'Doğal Uydu',
    radiusKm: '1,737 km (0.27× Dünya)',
    distFromSunAu: '1.00 AU (Dünya etrafında 384,400 km)',
    rotationPeriod: '27.3 gün (Kütleçekimsel Kilitli)',
    orbitPeriod: '27.3 gün',
    moonsCount: '0',
    atmosphere: 'Yok (Çok ince egzozfer)',
    funFactTr: 'Kütleçekim kilitlenmesi nedeniyle Dünya\'dan her zaman aynı yüzü görünür.',
  },
  mercury: {
    id: 'mercury',
    name: 'Mercury',
    nameTr: 'Merkür',
    emoji: '🪨',
    typeTr: 'Karasal Gezegen',
    radiusKm: '2,439 km (0.38× Dünya)',
    distFromSunAu: '0.39 AU (57.9 milyon km)',
    rotationPeriod: '58.6 gün',
    orbitPeriod: '88 gün',
    moonsCount: '0',
    atmosphere: 'Yok (Oksijen, Sodyum izleri)',
    funFactTr: 'Güneş\'e en yakın gezegendir; gündüz 430°C iken gece -180°C\'ye düşer.',
  },
  venus: {
    id: 'venus',
    name: 'Venus',
    nameTr: 'Venüs',
    emoji: '♀️',
    typeTr: 'Karasal Gezegen',
    radiusKm: '6,051 km (0.95× Dünya)',
    distFromSunAu: '0.72 AU (108.2 milyon km)',
    rotationPeriod: '243 gün (Ters Döner!)',
    orbitPeriod: '224.7 gün',
    moonsCount: '0',
    atmosphere: 'Karbondioksit (%96.5), Azot (%3.5)',
    funFactTr: 'Aşırı sera etkisi nedeniyle 465°C ile Güneş Sistemi\'nin en sıcak gezegenidir.',
  },
  mars: {
    id: 'mars',
    name: 'Mars',
    nameTr: 'Mars',
    emoji: '♂️',
    typeTr: 'Karasal Gezegen',
    radiusKm: '3,389 km (0.53× Dünya)',
    distFromSunAu: '1.52 AU (227.9 milyon km)',
    rotationPeriod: '24 saat 37 dk',
    orbitPeriod: '687 gün',
    moonsCount: '2 (Phobos, Deimos)',
    atmosphere: 'Karbondioksit (%95), Argon (%1.9)',
    funFactTr: 'Güneş Sistemi\'nin en yüksek dağı olan 21.9 km\'lik Olympus Mons bu gezegendedir.',
  },
  phobos: {
    id: 'phobos',
    name: 'Phobos',
    nameTr: 'Phobos',
    emoji: '🌑',
    typeTr: 'Mars Uydusu',
    radiusKm: '11.2 km',
    distFromSunAu: '1.52 AU (Mars etrafında 9,377 km)',
    rotationPeriod: '7.65 saat',
    orbitPeriod: '7.65 saat',
    moonsCount: '0',
    atmosphere: 'Yok',
    funFactTr: 'Mars\'a o kadar yakındır ki günde 3 kez Mars etrafında bir tur atar.',
  },
  deimos: {
    id: 'deimos',
    name: 'Deimos',
    nameTr: 'Deimos',
    emoji: '🌑',
    typeTr: 'Mars Uydusu',
    radiusKm: '6.2 km',
    distFromSunAu: '1.52 AU (Mars etrafında 23,460 km)',
    rotationPeriod: '30.3 saat',
    orbitPeriod: '30.3 saat',
    moonsCount: '0',
    atmosphere: 'Yok',
    funFactTr: 'Şekli patatese benzeyen küçük bir asteroit benzeri uydudur.',
  },
  jupiter: {
    id: 'jupiter',
    name: 'Jupiter',
    nameTr: 'Jüpiter',
    emoji: '🪐',
    typeTr: 'Gaz Devi',
    radiusKm: '69,911 km (11.2× Dünya)',
    distFromSunAu: '5.20 AU (778.5 milyon km)',
    rotationPeriod: '9 saat 55 dk (En Hızlı)',
    orbitPeriod: '11.86 yıl',
    moonsCount: '95 Bilinen Uydu',
    atmosphere: 'Hidrojen (%89), Helyum (%10)',
    funFactTr: 'Büyük Kırmızı Leke adı verilen dev fırtınası içine Dünya\'yı sığdırabilir.',
  },
  io: {
    id: 'io',
    name: 'Io',
    nameTr: 'Io',
    emoji: '🟡',
    typeTr: 'Jüpiter Uydusu (Galilean)',
    radiusKm: '1,821 km',
    distFromSunAu: '5.20 AU (Jüpiter etrafında 421,700 km)',
    rotationPeriod: '42.5 saat',
    orbitPeriod: '42.5 saat',
    moonsCount: '0',
    atmosphere: 'Kükürtdioksit izleri',
    funFactTr: 'Güneş Sistemi\'nin en aktif volkanik gök cismidir; 400\'den fazla aktif volkan barındırır.',
  },
  europa: {
    id: 'europa',
    name: 'Europa',
    nameTr: 'Europa',
    emoji: '🧊',
    typeTr: 'Jüpiter Uydusu (Galilean)',
    radiusKm: '1,560 km',
    distFromSunAu: '5.20 AU (Jüpiter etrafında 670,900 km)',
    rotationPeriod: '3.55 gün',
    orbitPeriod: '3.55 gün',
    moonsCount: '0',
    atmosphere: 'İnce Oksijen atmosferi',
    funFactTr: 'Buz tabakasının altında Dünya\'daki tüm okyanusların 2 katı büyüklüğünde sıvı su okyanusu vardır.',
  },
  ganymede: {
    id: 'ganymede',
    name: 'Ganymede',
    nameTr: 'Ganymede',
    emoji: '🌑',
    typeTr: 'Jüpiter Uydusu (Galilean)',
    radiusKm: '2,634 km (Merkür\'den Büyük!)',
    distFromSunAu: '5.20 AU (Jüpiter etrafında 1.07 milyon km)',
    rotationPeriod: '7.15 gün',
    orbitPeriod: '7.15 gün',
    moonsCount: '0',
    atmosphere: 'İnce Oksijen',
    funFactTr: 'Güneş Sistemi\'nin en büyük uydusudur ve kendi manyetik alanı olan tek uydudur.',
  },
  callisto: {
    id: 'callisto',
    name: 'Callisto',
    nameTr: 'Callisto',
    emoji: '🌑',
    typeTr: 'Jüpiter Uydusu (Galilean)',
    radiusKm: '2,410 km',
    distFromSunAu: '5.20 AU (Jüpiter etrafında 1.88 milyon km)',
    rotationPeriod: '16.69 gün',
    orbitPeriod: '16.69 gün',
    moonsCount: '0',
    atmosphere: 'Karbondioksit, Azot',
    funFactTr: 'Güneş Sistemi\'nde krater yoğunluğu en yüksek olan en eski yüzeye sahiptir.',
  },
  saturn: {
    id: 'saturn',
    name: 'Saturn',
    nameTr: 'Satürn',
    emoji: '🪐',
    typeTr: 'Gaz Devi',
    radiusKm: '58,232 km (9.45× Dünya)',
    distFromSunAu: '9.58 AU (1.43 milyar km)',
    rotationPeriod: '10 saat 33 dk',
    orbitPeriod: '29.45 yıl',
    moonsCount: '146 Bilinen Uydu',
    atmosphere: 'Hidrojen (%96), Helyum (%3)',
    funFactTr: 'Özgül ağırlığı sudan azdır; dev bir okyanusa konsaydı su üstünde yüzerdi.',
  },
  titan: {
    id: 'titan',
    name: 'Titan',
    nameTr: 'Titan',
    emoji: '🟡',
    typeTr: 'Satürn Uydusu',
    radiusKm: '2,574 km',
    distFromSunAu: '9.58 AU (Satürn etrafında 1.22 milyon km)',
    rotationPeriod: '15.94 gün',
    orbitPeriod: '15.94 gün',
    moonsCount: '0',
    atmosphere: 'Azot (%98.4), Metan (%1.4)',
    funFactTr: 'Yoğun atmosferi ve sıvı metan/etan gölleri olan tek uydudur.',
  },
  enceladus: {
    id: 'enceladus',
    name: 'Enceladus',
    nameTr: 'Enceladus',
    emoji: '🧊',
    typeTr: 'Satürn Uydusu',
    radiusKm: '252 km',
    distFromSunAu: '9.58 AU (Satürn etrafında 238,000 km)',
    rotationPeriod: '32.9 saat',
    orbitPeriod: '32.9 saat',
    moonsCount: '0',
    atmosphere: 'Su buharı gayzerleri',
    funFactTr: 'Güney kutbundan uzaya su buharı ve buz gayzerleri fışkırtır.',
  },
  uranus: {
    id: 'uranus',
    name: 'Uranus',
    nameTr: 'Uranüs',
    emoji: '🔵',
    typeTr: 'Buz Devi',
    radiusKm: '25,362 km (4.0× Dünya)',
    distFromSunAu: '19.22 AU (2.87 milyar km)',
    rotationPeriod: '17 saat 14 dk (Yan Yatar!)',
    orbitPeriod: '84.01 yıl',
    moonsCount: '28 Bilinen Uydu',
    atmosphere: 'Hidrojen (%83), Helyum (%15), Metan (%2)',
    funFactTr: '97.8° eksen eğikliği nedeniyle yörüngesinde adeta yan yatarak yuvarlanır.',
  },
  titania: {
    id: 'titania',
    name: 'Titania',
    nameTr: 'Titania',
    emoji: '🌑',
    typeTr: 'Uranüs Uydusu',
    radiusKm: '788 km',
    distFromSunAu: '19.22 AU (Uranüs etrafında 436,000 km)',
    rotationPeriod: '8.71 gün',
    orbitPeriod: '8.71 gün',
    moonsCount: '0',
    atmosphere: 'İnce Karbondioksit',
    funFactTr: 'Uranüs\'ün en büyük uydusudur ve devasa kanyon sistemleri barındırır.',
  },
  oberon: {
    id: 'oberon',
    name: 'Oberon',
    nameTr: 'Oberon',
    emoji: '🌑',
    typeTr: 'Uranüs Uydusu',
    radiusKm: '761 km',
    distFromSunAu: '19.22 AU (Uranüs etrafında 584,000 km)',
    rotationPeriod: '13.46 gün',
    orbitPeriod: '13.46 gün',
    moonsCount: '0',
    atmosphere: 'Yok',
    funFactTr: 'Uranüs\'ün en dıştaki büyük uydusudur, tabanı koyu renkli kraterlerle kaplıdır.',
  },
  neptune: {
    id: 'neptune',
    name: 'Neptune',
    nameTr: 'Neptün',
    emoji: '🔵',
    typeTr: 'Buz Devi',
    radiusKm: '24,622 km (3.88× Dünya)',
    distFromSunAu: '30.05 AU (4.50 milyar km)',
    rotationPeriod: '16 saat 6 dk',
    orbitPeriod: '164.79 yıl',
    moonsCount: '16 Bilinen Uydu',
    atmosphere: 'Hidrojen (%80), Helyum (%19), Metan (%1.5)',
    funFactTr: 'Saatle 2,100 km hıza ulaşan Güneş Sistemi\'nin en şiddetli rüzgarlarına sahiptir.',
  },
  triton: {
    id: 'triton',
    name: 'Triton',
    nameTr: 'Triton',
    emoji: '🌑',
    typeTr: 'Neptün Uydusu',
    radiusKm: '1,353 km',
    distFromSunAu: '30.05 AU (Neptün etrafında 354,800 km)',
    rotationPeriod: '5.88 gün (Ters Yörünge)',
    orbitPeriod: '5.88 gün',
    moonsCount: '0',
    atmosphere: 'Azot (%99), Metan izleri',
    funFactTr: 'Gezegeninin dönüş yönünün tersine (retrograd) dönen tek büyük uydudur.',
  },
  pluto: {
    id: 'pluto',
    name: 'Pluto',
    nameTr: 'Plüton',
    emoji: '⚪',
    typeTr: 'Cüce Gezegen (Kuiper Kuşağı)',
    radiusKm: '1,188 km (0.18× Dünya)',
    distFromSunAu: '39.48 AU (5.91 milyar km)',
    rotationPeriod: '6.39 gün',
    orbitPeriod: '248 yıl',
    moonsCount: '5 (Charon, Styx, Nix, Kerberos, Hydra)',
    atmosphere: 'Azot, Metan, Karbonmonoksit',
    funFactTr: 'Yüzeyinde azot buzullarından oluşan dev bir kalp şeklinde (Tombaugh Regio) bölge bulunur.',
  },
}
