import type { CelestialBodyId } from './planets'

export interface CelestialFact {
  id: CelestialBodyId
  name: string
  nameTr: string
  emoji: string
  typeTr: string // 'Karasal Gezegen' | 'Gaz Devi' | 'Buz Devi' | 'Cüce Gezegen' | 'Yıldız' | 'Doğal Uydu'
  radiusKm: string
  distFromSunAu: string
  rotationPeriod: string
  orbitPeriod: string
  moonsCount: string
  atmosphere: string
  funFactTr: string
}

export const CELESTIAL_FACTS: Record<CelestialBodyId, CelestialFact> = {
  sun: {
    id: 'sun',
    name: 'Sun',
    nameTr: 'Güneş',
    emoji: '☀️',
    typeTr: 'Sarı Cüce Yıldız (G2V)',
    radiusKm: '696,340 km (109× Dünya)',
    distFromSunAu: '0 AU (Merkez)',
    rotationPeriod: '25 - 35 gün',
    orbitPeriod: '230 milyon yıl (Samanyolu etrafında)',
    moonsCount: '8 Gezegen + Cüce Gezegenler',
    atmosphere: 'Hidrojen (%73), Helyum (%25)',
    funFactTr: 'Güneş Sistemimizin toplam kütlesinin %99.86\'sını tek başına oluşturur.',
  },
  earth: {
    id: 'earth',
    name: 'Earth',
    nameTr: 'Dünya',
    emoji: '🌍',
    typeTr: 'Karasal Gezegen',
    radiusKm: '6,371 km',
    distFromSunAu: '1.00 AU (149.6 milyon km)',
    rotationPeriod: '23 saat 56 dk',
    orbitPeriod: '365.25 gün',
    moonsCount: '1 (Ay)',
    atmosphere: 'Azot (%78), Oksijen (%21), Argon (%0.9)',
    funFactTr: 'Yüzeyinde sıvı halde su barındıran ve yaşamın bilindiği tek gök cismidir.',
  },
  moon: {
    id: 'moon',
    name: 'Moon',
    nameTr: 'Ay',
    emoji: '🌕',
    typeTr: 'Doğal Uydu',
    radiusKm: '1,737 km (0.27× Dünya)',
    distFromSunAu: '1.00 AU (Dünya etrafında 384,400 km)',
    rotationPeriod: '27.3 gün (Kütleçekimsel Kilitli)',
    orbitPeriod: '27.3 gün',
    moonsCount: '0',
    atmosphere: 'Yok (Çok ince egzozfer)',
    funFactTr: 'Kütleçekim kilitlenmesi nedeniyle Dünya\'dan her zaman aynı yüzü görünür.',
  },
  mercury: {
    id: 'mercury',
    name: 'Mercury',
    nameTr: 'Merkür',
    emoji: '🪨',
    typeTr: 'Karasal Gezegen',
    radiusKm: '2,439 km (0.38× Dünya)',
    distFromSunAu: '0.39 AU (57.9 milyon km)',
    rotationPeriod: '58.6 gün',
    orbitPeriod: '88 gün',
    moonsCount: '0',
    atmosphere: 'Yok (Oksijen, Sodyum izleri)',
    funFactTr: 'Güneş\'e en yakın gezegendir; gündüz 430°C iken gece -180°C\'ye düşer.',
  },
  venus: {
    id: 'venus',
    name: 'Venus',
    nameTr: 'Venüs',
    emoji: '♀️',
    typeTr: 'Karasal Gezegen',
    radiusKm: '6,051 km (0.95× Dünya)',
    distFromSunAu: '0.72 AU (108.2 milyon km)',
    rotationPeriod: '243 gün (Ters Döner!)',
    orbitPeriod: '224.7 gün',
    moonsCount: '0',
    atmosphere: 'Karbondioksit (%96.5), Azot (%3.5)',
    funFactTr: 'Aşırı sera etkisi nedeniyle 465°C ile Güneş Sistemi\'nin en sıcak gezegenidir.',
  },
  mars: {
    id: 'mars',
    name: 'Mars',
    nameTr: 'Mars',
    emoji: '♂️',
    typeTr: 'Karasal Gezegen',
    radiusKm: '3,389 km (0.53× Dünya)',
    distFromSunAu: '1.52 AU (227.9 milyon km)',
    rotationPeriod: '24 saat 37 dk',
    orbitPeriod: '687 gün',
    moonsCount: '2 (Phobos, Deimos)',
    atmosphere: 'Karbondioksit (%95), Argon (%1.9)',
    funFactTr: 'Güneş Sistemi\'nin en yüksek dağı olan 21.9 km\'lik Olympus Mons bu gezegendedir.',
  },
  phobos: {
    id: 'phobos',
    name: 'Phobos',
    nameTr: 'Phobos',
    emoji: '🌑',
    typeTr: 'Mars Uydusu',
    radiusKm: '11.2 km',
    distFromSunAu: '1.52 AU (Mars etrafında 9,377 km)',
    rotationPeriod: '7.65 saat',
    orbitPeriod: '7.65 saat',
    moonsCount: '0',
    atmosphere: 'Yok',
    funFactTr: 'Mars\'a o kadar yakındır ki günde 3 kez Mars etrafında bir tur atar.',
  },
  deimos: {
    id: 'deimos',
    name: 'Deimos',
    nameTr: 'Deimos',
    emoji: '🌑',
    typeTr: 'Mars Uydusu',
    radiusKm: '6.2 km',
    distFromSunAu: '1.52 AU (Mars etrafında 23,460 km)',
    rotationPeriod: '30.3 saat',
    orbitPeriod: '30.3 saat',
    moonsCount: '0',
    atmosphere: 'Yok',
    funFactTr: 'Şekli patatese benzeyen küçük bir asteroit benzeri uydudur.',
  },
  jupiter: {
    id: 'jupiter',
    name: 'Jupiter',
    nameTr: 'Jüpiter',
    emoji: '🪐',
    typeTr: 'Gaz Devi',
    radiusKm: '69,911 km (11.2× Dünya)',
    distFromSunAu: '5.20 AU (778.5 milyon km)',
    rotationPeriod: '9 saat 55 dk (En Hızlı)',
    orbitPeriod: '11.86 yıl',
    moonsCount: '101 Bilinen Uydu',
    atmosphere: 'Hidrojen (%89), Helyum (%10)',
    funFactTr: 'Büyük Kırmızı Leke adı verilen dev fırtınası içine Dünya\'yı sığdırabilir.',
  },
  io: {
    id: 'io',
    name: 'Io',
    nameTr: 'Io',
    emoji: '🟡',
    typeTr: 'Jüpiter Uydusu (Galilean)',
    radiusKm: '1,821 km',
    distFromSunAu: '5.20 AU (Jüpiter etrafında 421,700 km)',
    rotationPeriod: '42.5 saat',
    orbitPeriod: '42.5 saat',
    moonsCount: '0',
    atmosphere: 'Kükürtdioksit izleri',
    funFactTr: 'Güneş Sistemi\'nin en aktif volkanik gök cismidir; 400\'den fazla aktif volkan barındırır.',
  },
  europa: {
    id: 'europa',
    name: 'Europa',
    nameTr: 'Europa',
    emoji: '🧊',
    typeTr: 'Jüpiter Uydusu (Galilean)',
    radiusKm: '1,560 km',
    distFromSunAu: '5.20 AU (Jüpiter etrafında 670,900 km)',
    rotationPeriod: '3.55 gün',
    orbitPeriod: '3.55 gün',
    moonsCount: '0',
    atmosphere: 'İnce Oksijen atmosferi',
    funFactTr: 'Buz tabakasının altında Dünya\'daki tüm okyanusların 2 katı büyüklüğünde sıvı su okyanusu vardır.',
  },
  ganymede: {
    id: 'ganymede',
    name: 'Ganymede',
    nameTr: 'Ganymede',
    emoji: '🌑',
    typeTr: 'Jüpiter Uydusu (Galilean)',
    radiusKm: '2,634 km (Merkür\'den Büyük!)',
    distFromSunAu: '5.20 AU (Jüpiter etrafında 1.07 milyon km)',
    rotationPeriod: '7.15 gün',
    orbitPeriod: '7.15 gün',
    moonsCount: '0',
    atmosphere: 'İnce Oksijen',
    funFactTr: 'Güneş Sistemi\'nin en büyük uydusudur ve kendi manyetik alanı olan tek uydudur.',
  },
  callisto: {
    id: 'callisto',
    name: 'Callisto',
    nameTr: 'Callisto',
    emoji: '🌑',
    typeTr: 'Jüpiter Uydusu (Galilean)',
    radiusKm: '2,410 km',
    distFromSunAu: '5.20 AU (Jüpiter etrafında 1.88 milyon km)',
    rotationPeriod: '16.69 gün',
    orbitPeriod: '16.69 gün',
    moonsCount: '0',
    atmosphere: 'Çok ince CO₂, Oksijen ve Hidrojen egzosferi',
    funFactTr: 'Güneş Sistemi\'nde krater yoğunluğu en yüksek olan en eski yüzeye sahiptir.',
  },
  saturn: {
    id: 'saturn',
    name: 'Saturn',
    nameTr: 'Satürn',
    emoji: '🪐',
    typeTr: 'Gaz Devi',
    radiusKm: '58,232 km (9.45× Dünya)',
    distFromSunAu: '9.58 AU (1.43 milyar km)',
    rotationPeriod: '10 saat 33 dk',
    orbitPeriod: '29.45 yıl',
    moonsCount: '274 Bilinen Uydu',
    atmosphere: 'Hidrojen (%96), Helyum (%3)',
    funFactTr: 'Özgül ağırlığı sudan azdır; dev bir okyanusa konsaydı su üstünde yüzerdi.',
  },
  titan: {
    id: 'titan',
    name: 'Titan',
    nameTr: 'Titan',
    emoji: '🟡',
    typeTr: 'Satürn Uydusu',
    radiusKm: '2,574 km',
    distFromSunAu: '9.58 AU (Satürn etrafında 1.22 milyon km)',
    rotationPeriod: '15.94 gün',
    orbitPeriod: '15.94 gün',
    moonsCount: '0',
    atmosphere: 'Azot (%95), Metan (%5)',
    funFactTr: 'Yoğun atmosferi ve sıvı metan/etan gölleri olan tek uydudur.',
  },
  enceladus: {
    id: 'enceladus',
    name: 'Enceladus',
    nameTr: 'Enceladus',
    emoji: '🧊',
    typeTr: 'Satürn Uydusu',
    radiusKm: '252 km',
    distFromSunAu: '9.58 AU (Satürn etrafında 238,000 km)',
    rotationPeriod: '32.9 saat',
    orbitPeriod: '32.9 saat',
    moonsCount: '0',
    atmosphere: 'Su buharı gayzerleri',
    funFactTr: 'Güney kutbundan uzaya su buharı ve buz gayzerleri fışkırtır.',
  },
  mimas: {
    id: 'mimas', name: 'Mimas', nameTr: 'Mimas', emoji: '🌑',
    typeTr: 'Satürn Uydusu', radiusKm: '198 km',
    distFromSunAu: '9.58 AU (Satürn etrafında 185,539 km)',
    rotationPeriod: '22 saat 37 dk', orbitPeriod: '22 saat 37 dk',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Herschel krateri, küçük uydunun çapının yaklaşık üçte biri kadardır.',
  },
  tethys: {
    id: 'tethys', name: 'Tethys', nameTr: 'Tethys', emoji: '🌑',
    typeTr: 'Satürn Uydusu', radiusKm: '531 km',
    distFromSunAu: '9.58 AU (Satürn etrafında 294,619 km)',
    rotationPeriod: '1.89 gün', orbitPeriod: '1.89 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Yüzeyinin büyük bölümü su buzundan oluşur ve dev Ithaca Chasma vadisini taşır.',
  },
  dione: {
    id: 'dione', name: 'Dione', nameTr: 'Dione', emoji: '🌑',
    typeTr: 'Satürn Uydusu', radiusKm: '561 km',
    distFromSunAu: '9.58 AU (Satürn etrafında 377,396 km)',
    rotationPeriod: '2.74 gün', orbitPeriod: '2.74 gün',
    moonsCount: '0', atmosphere: 'Çok ince Oksijen egzosferi',
    funFactTr: 'Buz kabuğunun altında küresel bir okyanus bulunabileceğine dair kanıtlar vardır.',
  },
  rhea: {
    id: 'rhea', name: 'Rhea', nameTr: 'Rhea', emoji: '🌑',
    typeTr: 'Satürn Uydusu', radiusKm: '764 km',
    distFromSunAu: '9.58 AU (Satürn etrafında 527,108 km)',
    rotationPeriod: '4.52 gün', orbitPeriod: '4.52 gün',
    moonsCount: '0', atmosphere: 'Çok ince Oksijen ve Karbondioksit egzosferi',
    funFactTr: 'Satürn’ün ikinci büyük uydusudur; buz ve kayadan oluşan yoğun kraterli bir dünyadır.',
  },
  iapetus: {
    id: 'iapetus', name: 'Iapetus', nameTr: 'Iapetus', emoji: '◐',
    typeTr: 'Satürn Uydusu', radiusKm: '735 km',
    distFromSunAu: '9.58 AU (Satürn etrafında 3.56 milyon km)',
    rotationPeriod: '79.32 gün', orbitPeriod: '79.32 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Bir yarısı çok koyu, diğer yarısı parlaktır; ekvatorunda dev bir sırt uzanır.',
  },
  uranus: {
    id: 'uranus',
    name: 'Uranus',
    nameTr: 'Uranüs',
    emoji: '🔵',
    typeTr: 'Buz Devi',
    radiusKm: '25,362 km (4.0× Dünya)',
    distFromSunAu: '19.22 AU (2.87 milyar km)',
    rotationPeriod: '17 saat 14 dk (Yan Yatar!)',
    orbitPeriod: '84.01 yıl',
    moonsCount: '28 Bilinen Uydu',
    atmosphere: 'Hidrojen (%83), Helyum (%15), Metan (%2)',
    funFactTr: '97.8° eksen eğikliği nedeniyle yörüngesinde adeta yan yatarak yuvarlanır.',
  },
  miranda: {
    id: 'miranda', name: 'Miranda', nameTr: 'Miranda', emoji: '🌑',
    typeTr: 'Uranüs Uydusu', radiusKm: '236 km',
    distFromSunAu: '19.22 AU (Uranüs etrafında 129,390 km)',
    rotationPeriod: '1.41 gün', orbitPeriod: '1.41 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Bir araya dikilmiş gibi görünen sıra dışı arazileri ve dev uçurumları vardır.',
  },
  ariel: {
    id: 'ariel', name: 'Ariel', nameTr: 'Ariel', emoji: '🌑',
    typeTr: 'Uranüs Uydusu', radiusKm: '579 km',
    distFromSunAu: '19.22 AU (Uranüs etrafında 190,900 km)',
    rotationPeriod: '2.52 gün', orbitPeriod: '2.52 gün',
    moonsCount: '0', atmosphere: 'Çok ince Karbondioksit',
    funFactTr: 'Uranüs’ün büyük uyduları arasında en parlak ve en genç yüzeylerden birine sahiptir.',
  },
  umbriel: {
    id: 'umbriel', name: 'Umbriel', nameTr: 'Umbriel', emoji: '🌑',
    typeTr: 'Uranüs Uydusu', radiusKm: '585 km',
    distFromSunAu: '19.22 AU (Uranüs etrafında 266,000 km)',
    rotationPeriod: '4.14 gün', orbitPeriod: '4.14 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Uranüs’ün büyük uyduları içindeki en koyu yüzeylerden birine sahiptir.',
  },
  titania: {
    id: 'titania',
    name: 'Titania',
    nameTr: 'Titania',
    emoji: '🌑',
    typeTr: 'Uranüs Uydusu',
    radiusKm: '788 km',
    distFromSunAu: '19.22 AU (Uranüs etrafında 436,000 km)',
    rotationPeriod: '8.71 gün',
    orbitPeriod: '8.71 gün',
    moonsCount: '0',
    atmosphere: 'İnce Karbondioksit',
    funFactTr: 'Uranüs\'ün en büyük uydusudur ve devasa kanyon sistemleri barındırır.',
  },
  oberon: {
    id: 'oberon',
    name: 'Oberon',
    nameTr: 'Oberon',
    emoji: '🌑',
    typeTr: 'Uranüs Uydusu',
    radiusKm: '761 km',
    distFromSunAu: '19.22 AU (Uranüs etrafında 584,000 km)',
    rotationPeriod: '13.46 gün',
    orbitPeriod: '13.46 gün',
    moonsCount: '0',
    atmosphere: 'Yok',
    funFactTr: 'Uranüs\'ün en dıştaki büyük uydusudur, tabanı koyu renkli kraterlerle kaplıdır.',
  },
  neptune: {
    id: 'neptune',
    name: 'Neptune',
    nameTr: 'Neptün',
    emoji: '🔵',
    typeTr: 'Buz Devi',
    radiusKm: '24,622 km (3.88× Dünya)',
    distFromSunAu: '30.05 AU (4.50 milyar km)',
    rotationPeriod: '16 saat 6 dk',
    orbitPeriod: '164.79 yıl',
    moonsCount: '16 Bilinen Uydu',
    atmosphere: 'Hidrojen (%80), Helyum (%19), Metan (%1.5)',
    funFactTr: 'Saatte 2,000 km hızı aşan Güneş Sistemi\'nin en şiddetli rüzgarlarına sahiptir.',
  },
  proteus: {
    id: 'proteus', name: 'Proteus', nameTr: 'Proteus', emoji: '🌑',
    typeTr: 'Neptün Uydusu', radiusKm: '210 km',
    distFromSunAu: '30.05 AU (Neptün etrafında 117,646 km)',
    rotationPeriod: '1.12 gün', orbitPeriod: '1.12 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Kütleçekiminin küresel biçime zorlamadığı en büyük düzensiz uydulardan biridir.',
  },
  nereid: {
    id: 'nereid', name: 'Nereid', nameTr: 'Nereid', emoji: '🌑',
    typeTr: 'Neptün Uydusu', radiusKm: '170 km',
    distFromSunAu: '30.05 AU (Neptün etrafında ortalama 5.51 milyon km)',
    rotationPeriod: 'Yaklaşık 11.6 saat', orbitPeriod: '360.14 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Güneş Sistemi’ndeki uydular arasında en dışmerkez yörüngelerden birine sahiptir.',
  },
  triton: {
    id: 'triton',
    name: 'Triton',
    nameTr: 'Triton',
    emoji: '🌑',
    typeTr: 'Neptün Uydusu',
    radiusKm: '1,353 km',
    distFromSunAu: '30.05 AU (Neptün etrafında 354,800 km)',
    rotationPeriod: '5.88 gün (Ters Yörünge)',
    orbitPeriod: '5.88 gün',
    moonsCount: '0',
    atmosphere: 'Azot (%99), Metan izleri',
    funFactTr: 'Gezegeninin dönüş yönünün tersine (retrograd) dönen tek büyük uydudur.',
  },
  pluto: {
    id: 'pluto',
    name: 'Pluto',
    nameTr: 'Plüton',
    emoji: '⚪',
    typeTr: 'Cüce Gezegen (Kuiper Kuşağı)',
    radiusKm: '1,188 km (0.18× Dünya)',
    distFromSunAu: '39.48 AU (5.91 milyar km)',
    rotationPeriod: '6.39 gün',
    orbitPeriod: '248 yıl',
    moonsCount: '5 (Charon, Styx, Nix, Kerberos, Hydra)',
    atmosphere: 'Azot, Metan, Karbonmonoksit',
    funFactTr: 'Yüzeyinde azot buzullarından oluşan dev bir kalp şeklinde (Tombaugh Regio) bölge bulunur.',
  },
  charon: {
    id: 'charon', name: 'Charon', nameTr: 'Charon', emoji: '🌑',
    typeTr: 'Plüton Uydusu', radiusKm: '606 km',
    distFromSunAu: '39.48 AU (Plüton etrafında 19,596 km)',
    rotationPeriod: '6.39 gün', orbitPeriod: '6.39 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Plüton’a göre o kadar büyüktür ki ikisi ortak kütle merkezi çevresinde çift sistem gibi döner.',
  },
  amalthea: {
    id: 'amalthea', name: 'Amalthea', nameTr: 'Amalthea', emoji: '🔴',
    typeTr: 'Jüpiter Uydusu', radiusKm: '83.5 km (ortalama)',
    distFromSunAu: '5.20 AU (Jüpiter etrafında 181,365 km)',
    rotationPeriod: '11 saat 57 dk', orbitPeriod: '11 saat 57 dk',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Jüpiter’in küçük iç uydularının en büyüğüdür ve Amalthea halkasının malzemesine katkı sağlar.',
  },
  himalia: {
    id: 'himalia', name: 'Himalia', nameTr: 'Himalia', emoji: '🌑',
    typeTr: 'Jüpiter Uydusu', radiusKm: '85 km (ortalama)',
    distFromSunAu: '5.20 AU (Jüpiter etrafında yaklaşık 11.46 milyon km)',
    rotationPeriod: 'Yaklaşık 7.8 saat', orbitPeriod: '250.56 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Jüpiter’in düzensiz prograd uydularından oluşan Himalia grubunun en büyük üyesidir.',
  },
  pan: {
    id: 'pan', name: 'Pan', nameTr: 'Pan', emoji: '🛸',
    typeTr: 'Satürn Uydusu', radiusKm: '14.1 km (ortalama)',
    distFromSunAu: '9.58 AU (Satürn etrafında 133,584 km)',
    rotationPeriod: '13 saat 48 dk', orbitPeriod: '13 saat 48 dk',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Satürn’ün A halkasındaki Encke Boşluğu içinde döner ve ekvator sırtıyla tabak görünümündedir.',
  },
  hyperion: {
    id: 'hyperion', name: 'Hyperion', nameTr: 'Hyperion', emoji: '🌑',
    typeTr: 'Satürn Uydusu', radiusKm: '135 km (ortalama)',
    distFromSunAu: '9.58 AU (Satürn etrafında 1.48 milyon km)',
    rotationPeriod: 'Kaotik', orbitPeriod: '21.28 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Sünger benzeri gözenekli yüzeyi ve öngörülemeyen kaotik dönüşüyle tanınır.',
  },
  larissa: {
    id: 'larissa', name: 'Larissa', nameTr: 'Larissa', emoji: '🌑',
    typeTr: 'Neptün Uydusu', radiusKm: '97 km (ortalama)',
    distFromSunAu: '30.05 AU (Neptün etrafında 73,548 km)',
    rotationPeriod: '13 saat 19 dk', orbitPeriod: '13 saat 19 dk',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Düzensiz biçimli Larissa, Neptün’ün halkalarının hemen dışında hızlı bir yörüngede dolanır.',
  },
  styx: {
    id: 'styx', name: 'Styx', nameTr: 'Styx', emoji: '🌑',
    typeTr: 'Plüton Uydusu', radiusKm: 'Yaklaşık 5 km',
    distFromSunAu: '39.48 AU (Plüton sisteminde 42,656 km)',
    rotationPeriod: 'Kaotik', orbitPeriod: '20.16 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Plüton’un bilinen en küçük ve en içteki küçük uydusudur.',
  },
  nix: {
    id: 'nix', name: 'Nix', nameTr: 'Nix', emoji: '🌑',
    typeTr: 'Plüton Uydusu', radiusKm: 'Yaklaşık 20 km',
    distFromSunAu: '39.48 AU (Plüton sisteminde 48,694 km)',
    rotationPeriod: 'Kaotik', orbitPeriod: '24.85 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'New Horizons, Nix’in uzamış şeklini ve beklenmedik kırmızımsı bir kraterini görüntüledi.',
  },
  kerberos: {
    id: 'kerberos', name: 'Kerberos', nameTr: 'Kerberos', emoji: '🌑',
    typeTr: 'Plüton Uydusu', radiusKm: 'Yaklaşık 6 km',
    distFromSunAu: '39.48 AU (Plüton sisteminde 57,783 km)',
    rotationPeriod: 'Kaotik', orbitPeriod: '32.17 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'İki küçük lobdan oluşan parlak yüzeyli bir temas ikilisi olabilir.',
  },
  hydra: {
    id: 'hydra', name: 'Hydra', nameTr: 'Hydra', emoji: '🌑',
    typeTr: 'Plüton Uydusu', radiusKm: 'Yaklaşık 22 km',
    distFromSunAu: '39.48 AU (Plüton sisteminde 64,738 km)',
    rotationPeriod: 'Kaotik', orbitPeriod: '38.20 gün',
    moonsCount: '0', atmosphere: 'Yok',
    funFactTr: 'Plüton sistemindeki küçük uyduların en dışta dolananıdır ve su buzu bakımından zengindir.',
  },
  ceres: {
    id: 'ceres', name: 'Ceres', nameTr: 'Ceres', emoji: '⚪',
    typeTr: 'Cüce Gezegen (Ana Asteroit Kuşağı)', radiusKm: '470 km',
    distFromSunAu: '2.77 AU', rotationPeriod: '9 saat 4 dk', orbitPeriod: '4.60 yıl',
    moonsCount: '0', atmosphere: 'Çok ince su buharı izleri',
    funFactTr: 'Dawn görevi, Occator Krateri içindeki parlak tuz birikimlerini ve geçmiş sıvı etkinliğini ortaya çıkardı.',
  },
  haumea: {
    id: 'haumea', name: 'Haumea', nameTr: 'Haumea', emoji: '⚪',
    typeTr: 'Cüce Gezegen (Kuiper Kuşağı)', radiusKm: 'Yaklaşık 780 km (ortalama)',
    distFromSunAu: '43.13 AU', rotationPeriod: '3 saat 55 dk', orbitPeriod: '284 yıl',
    moonsCount: '2 (Hiʻiaka, Namaka)', atmosphere: 'Doğrulanmış kalıcı atmosfer yok',
    funFactTr: 'Çok hızlı dönüşü Haumea’yı uzatır; ayrıca bir halkası olduğu bilinen ilk cüce gezegendir.',
  },
  makemake: {
    id: 'makemake', name: 'Makemake', nameTr: 'Makemake', emoji: '⚪',
    typeTr: 'Cüce Gezegen (Kuiper Kuşağı)', radiusKm: 'Yaklaşık 715 km',
    distFromSunAu: '45.79 AU', rotationPeriod: '22 saat 50 dk', orbitPeriod: '306 yıl',
    moonsCount: '1 (MK2)', atmosphere: 'Güneş’e uzak konumda küresel atmosfer saptanmadı',
    funFactTr: 'Yüzeyindeki donmuş metan ve etan, Makemake’ye kırmızımsı bir renk verir.',
  },
  eris: {
    id: 'eris', name: 'Eris', nameTr: 'Eris', emoji: '⚪',
    typeTr: 'Cüce Gezegen (Dağınık Disk)', radiusKm: '1,163 km',
    distFromSunAu: '67.78 AU (yarı-büyük eksen)', rotationPeriod: '25.9 saat',
    orbitPeriod: '558 yıl', moonsCount: '1 (Dysnomia)',
    atmosphere: 'Kalıcı atmosfer doğrulanmadı',
    funFactTr: 'Eris’in keşfi, gezegen tanımının yeniden ele alınmasına ve cüce gezegen sınıfının oluşturulmasına katkı sağladı.',
  },
}

export const CELESTIAL_FUN_FACTS_EN: Record<CelestialBodyId, string> = {
  sun: 'The Sun contains about 99.86% of the Solar System’s total mass.',
  earth: 'Earth is the only known world with stable surface liquid water and life.',
  moon: 'Tidal locking keeps nearly the same lunar hemisphere facing Earth.',
  mercury: 'Mercury ranges from about 430°C by day to −180°C at night.',
  venus: 'A runaway greenhouse effect makes Venus the hottest planet at about 465°C.',
  mars: 'Mars hosts Olympus Mons, the tallest known volcano in the Solar System.',
  phobos: 'Phobos circles Mars roughly three times during each Martian day.',
  deimos: 'Deimos is a small, irregular, asteroid-like moon of Mars.',
  jupiter: 'Jupiter’s Great Red Spot is a giant, long-lived atmospheric storm.',
  io: 'Io is the Solar System’s most volcanically active known world.',
  europa: 'Europa likely hides a global salty ocean beneath its icy crust.',
  ganymede: 'Ganymede is the largest moon and the only moon with an intrinsic magnetic field.',
  callisto: 'Callisto preserves one of the oldest and most heavily cratered surfaces known.',
  amalthea: 'Amalthea is Jupiter’s largest inner moon and supplies material to its faint ring.',
  himalia: 'Himalia is the largest member of Jupiter’s distant prograde Himalia group.',
  saturn: 'Saturn’s average density is lower than that of liquid water.',
  pan: 'Pan orbits inside the Encke Gap and has a distinctive equatorial ridge.',
  titan: 'Titan is the only moon with a dense atmosphere and stable surface lakes.',
  enceladus: 'Enceladus vents water-rich plumes from fractures near its south pole.',
  mimas: 'The Herschel crater spans roughly one third of Mimas’s diameter.',
  tethys: 'Tethys is mostly water ice and carries the enormous Ithaca Chasma.',
  dione: 'Evidence suggests Dione may contain a global ocean beneath its ice shell.',
  rhea: 'Rhea is Saturn’s second-largest moon, built mainly from ice and rock.',
  iapetus: 'Iapetus has contrasting bright and dark hemispheres and a giant equatorial ridge.',
  hyperion: 'Hyperion is known for its sponge-like surface and chaotic rotation.',
  uranus: 'Uranus rotates on its side because its axial tilt is about 97.8°.',
  miranda: 'Miranda has patchwork terrain and some of the tallest known cliffs.',
  ariel: 'Ariel has one of the brightest and geologically youngest Uranian moon surfaces.',
  umbriel: 'Umbriel is among the darkest of Uranus’s large moons.',
  titania: 'Titania is Uranus’s largest moon and carries enormous canyon systems.',
  oberon: 'Oberon is the outermost large Uranian moon and has dark-floored craters.',
  neptune: 'Neptune has the fastest measured planetary winds, exceeding 2,000 km/h.',
  larissa: 'Irregular Larissa circles Neptune rapidly just beyond the ring system.',
  proteus: 'Proteus is one of the largest irregular moons not rounded by its own gravity.',
  nereid: 'Nereid follows one of the most eccentric known satellite orbits.',
  triton: 'Triton is the only large moon with a retrograde orbit around its planet.',
  pluto: 'Pluto’s Tombaugh Regio contains a vast heart-shaped plain of nitrogen ice.',
  charon: 'Pluto and Charon orbit a barycenter located outside Pluto itself.',
  styx: 'Styx is the smallest and innermost of Pluto’s four tiny outer moons.',
  nix: 'New Horizons revealed Nix’s elongated shape and an unexpectedly reddish crater.',
  kerberos: 'Kerberos may be a bright contact binary made from two small lobes.',
  hydra: 'Hydra is Pluto’s outermost small moon and has a water-ice-rich surface.',
  ceres: 'Dawn found bright salts and evidence of past liquid activity in Occator crater.',
  haumea: 'Haumea’s rapid spin elongates it; it was the first dwarf planet found with a ring.',
  makemake: 'Frozen methane and ethane give Makemake a reddish surface.',
  eris: 'Eris helped trigger the modern planet definition and dwarf-planet category.',
}

const ENGLISH_VALUE_REPLACEMENTS: ReadonlyArray<readonly [string, string]> = [
  ['Kütleçekimsel Kilitli', 'Tidally locked'],
  ['Ters Yörünge', 'Retrograde orbit'],
  ['Ters Döner!', 'Retrograde'],
  ['Bilinen Uydu', 'known moons'],
  ['Cüce Gezegenler', 'dwarf planets'],
  ['Çok ince', 'Very thin'],
  ['Doğrulanmış kalıcı atmosfer yok', 'No confirmed permanent atmosphere'],
  ['Kalıcı atmosfer doğrulanmadı', 'No permanent atmosphere confirmed'],
  ['Güneş’e uzak konumda küresel atmosfer saptanmadı', 'No global atmosphere detected at current solar distance'],
  ['Global Okyanus & Kabuk', 'global ocean and ice shell'],
  ['Anortozit Kraterler', 'anorthosite craters'],
  ['Devasa Kanyonlar', 'enormous canyons'],
  ['Kraterli Buz ve Kaya', 'cratered ice and rock'],
  ['Tozlu Kaya', 'dusty rock'],
  ['Yan Yatan Eksen', 'sideways axial tilt'],
  ['Azot Gayzerleri', 'nitrogen geysers'],
  ['Seyrek Oksijen', 'tenuous oxygen'],
  ['Su buharı ağırlıklı ince egzozfer', 'thin water-vapor exosphere'],
  ['İnce Oksijen Egzozferi', 'thin oxygen exosphere'],
  ['Sıvı Metan Gölleri ve Denizleri', 'liquid methane lakes and seas'],
  ['Su buharı gayzerleri', 'Water-vapor plumes'],
  ['su buharı', 'water vapor'],
  ['Karbonmonoksit', 'carbon monoxide'],
  ['Karbondioksit', 'carbon dioxide'],
  ['Hidrojen', 'hydrogen'],
  ['Helyum', 'helium'],
  ['Oksijen', 'oxygen'],
  ['Azot', 'nitrogen'],
  ['Argon', 'argon'],
  ['Metan', 'methane'],
  ['Sodyum', 'sodium'],
  ['Kükürtdioksit', 'sulfur dioxide'],
  ['Sülfürik Asit Yağmurları', 'sulfuric-acid clouds'],
  ['Sıvı Su Okyanusları', 'liquid-water oceans'],
  ['Tektonik Buz Çatlakları', 'tectonic ice fractures'],
  ['Kadim Kraterleşmiş Yüzey', 'ancient cratered surface'],
  ['Aktif Yanardağ', 'active volcanoes'],
  ['Buz Kabuğu ve Su Gayzerleri', 'ice crust and water plumes'],
  ['Devasa Gaz Fırtınaları', 'giant gas storms'],
  ['Supersonik Rüzgarlar', 'supersonic winds'],
  ['Fırtınalar', 'storms'],
  ['Kızıl Regolit & Devasa Toz', 'red regolith and vast dust'],
  ['Azot & Karbonmonoksit Buzları', 'nitrogen and carbon-monoxide ices'],
  ['İzleri', 'traces'],
  ['İnce', 'thin'],
  ['ağırlıklı', 'dominated'],
  ['Gayzerleri', 'geysers'],
  ['Rüzgarlar', 'winds'],
  ['Buzları', 'ices'],
  ['Devasa', 'vast'],
  ['Ortalama', 'mean'],
  ['Milyon', 'million'],
  ['Kraterler', 'craters'],
  ['ile', 'to'],
  ['Yüzey', 'surface'],
  ['Çekirdek', 'core'],
  ['Gece', 'night'],
  ['Gündüz', 'day'],
  ['egzozfer', 'exosphere'],
  ['egzosferi', 'exosphere'],
  ['izleri', 'traces'],
  ['Merkez', 'Center'],
  ['Dünya etrafında', 'orbiting Earth at'],
  ['Mars etrafında', 'orbiting Mars at'],
  ['Jüpiter etrafında', 'orbiting Jupiter at'],
  ['Satürn etrafında', 'orbiting Saturn at'],
  ['Uranüs etrafında', 'orbiting Uranus at'],
  ['Neptün etrafında', 'orbiting Neptune at'],
  ['Plüton etrafında', 'orbiting Pluto at'],
  ['Plüton sisteminde', 'in the Pluto system at'],
  ['Samanyolu etrafında', 'around the Milky Way'],
  ['ortalama', 'mean'],
  ['Yaklaşık', 'Approx.'],
  ['Kaotik', 'Chaotic'],
  ['Yok', 'None'],
  ['Dünya', 'Earth'],
  ['milyon', 'million'],
  ['milyar', 'billion'],
  ['saat', 'hours'],
  ['gün', 'days'],
  ['yıl', 'years'],
  ['dk', 'min'],
] as const

export function celestialValueEn(value: string): string {
  return ENGLISH_VALUE_REPLACEMENTS.reduce(
    (translated, [source, target]) => translated.replaceAll(source, target),
    value,
  )
}

export function celestialTypeEn(typeTr: string): string {
  if (typeTr.includes('Yıldız')) return 'Star'
  if (typeTr.includes('Karasal')) return 'Terrestrial Planet'
  if (typeTr.includes('Gaz Devi')) return 'Gas Giant'
  if (typeTr.includes('Buz Devi')) return 'Ice Giant'
  if (typeTr.includes('Cüce Gezegen')) return 'Dwarf Planet'
  if (typeTr.includes('Uydu')) return 'Natural Satellite'
  return celestialValueEn(typeTr)
}
