export interface SurfaceSite {
  id: string
  bodyId: 'earth' | 'moon' | 'mars' | 'venus' | 'titan'
  kind?: 'landing' | 'launch' | 'observatory' | 'ground-station'
  name: string
  nameTr: string
  year: number
  agency: string
  agencyTr: string
  lat: number
  lon: number
  emoji: string
  detailsTr: string
  detailsEn?: string
  sourceUrl: string
}

export type LandingSite = SurfaceSite

export const LANDING_SITES: SurfaceSite[] = [
  // 🌍 EARTH OBSERVATORIES, LAUNCH SITES AND DEEP SPACE NETWORK
  {
    id: 'kennedy-space-center',
    bodyId: 'earth',
    kind: 'launch',
    name: 'Kennedy Space Center',
    nameTr: 'Kennedy Uzay Merkezi',
    year: 1962,
    agency: 'NASA (USA)',
    agencyTr: 'NASA (ABD)',
    lat: 28.5721,
    lon: -80.648,
    emoji: '🚀',
    detailsTr: 'Apollo ve Uzay Mekiği programlarının ana fırlatma merkezi; günümüzde Artemis görevlerine ev sahipliği yapıyor.',
    detailsEn: 'The primary launch center for Apollo and the Space Shuttle, now supporting Artemis missions.',
    sourceUrl: 'https://www.nasa.gov/kennedy/',
  },
  {
    id: 'baikonur-cosmodrome',
    bodyId: 'earth',
    kind: 'launch',
    name: 'Baikonur Cosmodrome',
    nameTr: 'Baykonur Kozmodromu',
    year: 1955,
    agency: 'Roscosmos (Kazakhstan)',
    agencyTr: 'Roscosmos (Kazakistan)',
    lat: 45.965,
    lon: 63.305,
    emoji: '🚀',
    detailsTr: 'Sputnik 1 ve Yuri Gagarin’in Vostok 1 uçuşu dahil uzay çağının ilk kilometre taşlarının fırlatma alanıdır.',
    detailsEn: 'Launch site of early space-age milestones including Sputnik 1 and Yuri Gagarin aboard Vostok 1.',
    sourceUrl: 'https://www.esa.int/Enabling_Support/Space_Transportation/Launch_vehicles/Baikonur_launch_site',
  },
  {
    id: 'guiana-space-centre',
    bodyId: 'earth',
    kind: 'launch',
    name: 'Guiana Space Centre',
    nameTr: 'Guyana Uzay Merkezi',
    year: 1968,
    agency: 'CNES / ESA',
    agencyTr: 'CNES / ESA',
    lat: 5.239,
    lon: -52.768,
    emoji: '🚀',
    detailsTr: 'Ekvatora yakın konumu sayesinde doğuya yapılan fırlatmalarda Dünya’nın dönüşünden verimli biçimde yararlanır.',
    detailsEn: 'Its near-equatorial location efficiently uses Earth’s rotation for eastward launches.',
    sourceUrl: 'https://www.esa.int/Enabling_Support/Space_Transportation/Europe_s_Spaceport',
  },
  {
    id: 'satish-dhawan-space-centre',
    bodyId: 'earth',
    kind: 'launch',
    name: 'Satish Dhawan Space Centre',
    nameTr: 'Satish Dhawan Uzay Merkezi',
    year: 1971,
    agency: 'ISRO (India)',
    agencyTr: 'ISRO (Hindistan)',
    lat: 13.7199,
    lon: 80.2304,
    emoji: '🚀',
    detailsTr: 'Hindistan’ın PSLV, GSLV ve LVM3 araçları için ana yörünge fırlatma merkezidir.',
    detailsEn: 'India’s primary orbital launch center for PSLV, GSLV and LVM3 launch vehicles.',
    sourceUrl: 'https://www.isro.gov.in/SDSC.html',
  },
  {
    id: 'alma-observatory',
    bodyId: 'earth',
    kind: 'observatory',
    name: 'Atacama Large Millimeter/submillimeter Array',
    nameTr: 'ALMA Gözlemevi',
    year: 2013,
    agency: 'ESO / NAOJ / NRAO',
    agencyTr: 'ESO / NAOJ / NRAO',
    lat: -23.029,
    lon: -67.755,
    emoji: '🔭',
    detailsTr: 'Şili’deki Chajnantor Platosu’nda, soğuk gaz ve tozdan gelen milimetre-altı ışınımı inceleyen 66 antenli dizidir.',
    detailsEn: 'A 66-antenna array on Chile’s Chajnantor Plateau observing millimeter and submillimeter light from cold gas and dust.',
    sourceUrl: 'https://www.almaobservatory.org/en/about-alma-at-first-glance/',
  },
  {
    id: 'kandilli-observatory',
    bodyId: 'earth',
    kind: 'observatory',
    name: 'Kandilli Observatory',
    nameTr: 'Kandilli Rasathanesi',
    year: 1868,
    agency: 'Boğaziçi University (Türkiye)',
    agencyTr: 'Boğaziçi Üniversitesi (Türkiye)',
    lat: 41.062,
    lon: 29.066,
    emoji: '🔭',
    detailsTr: 'İstanbul’da astronomi, jeofizik, deprem izleme ve afet araştırmalarını sürdüren tarihî gözlemevidir.',
    detailsEn: 'A historic Istanbul observatory conducting astronomy, geophysics, earthquake monitoring and disaster research.',
    sourceUrl: 'https://www.koeri.boun.edu.tr/new/en',
  },
  {
    id: 'dsn-goldstone',
    bodyId: 'earth',
    kind: 'ground-station',
    name: 'Goldstone Deep Space Communications Complex',
    nameTr: 'Goldstone Derin Uzay İletişim Kompleksi',
    year: 1958,
    agency: 'NASA / JPL',
    agencyTr: 'NASA / JPL',
    lat: 35.2472,
    lon: -116.7933,
    emoji: '📡',
    detailsTr: 'NASA Derin Uzay Ağı’nın Amerika’daki anten kompleksi; uzak uzay araçlarıyla çift yönlü iletişim kurar.',
    detailsEn: 'The American antenna complex of NASA’s Deep Space Network, communicating with distant spacecraft.',
    sourceUrl: 'https://www.jpl.nasa.gov/missions/dsn/',
  },
  {
    id: 'dsn-madrid',
    bodyId: 'earth',
    kind: 'ground-station',
    name: 'Madrid Deep Space Communications Complex',
    nameTr: 'Madrid Derin Uzay İletişim Kompleksi',
    year: 1964,
    agency: 'NASA / JPL',
    agencyTr: 'NASA / JPL',
    lat: 40.4272,
    lon: -4.2506,
    emoji: '📡',
    detailsTr: 'NASA Derin Uzay Ağı’nın Avrupa istasyonu; Dünya dönerken uzay araçlarıyla kesintisiz bağlantıya katkı sağlar.',
    detailsEn: 'The European Deep Space Network station, helping maintain spacecraft contact as Earth rotates.',
    sourceUrl: 'https://www.jpl.nasa.gov/missions/dsn/',
  },
  {
    id: 'dsn-canberra',
    bodyId: 'earth',
    kind: 'ground-station',
    name: 'Canberra Deep Space Communication Complex',
    nameTr: 'Canberra Derin Uzay İletişim Kompleksi',
    year: 1965,
    agency: 'NASA / JPL',
    agencyTr: 'NASA / JPL',
    lat: -35.3983,
    lon: 148.9819,
    emoji: '📡',
    detailsTr: 'NASA Derin Uzay Ağı’nın güney yarımküredeki anten kompleksi ve üç kıtalı ağın üçüncü ayağıdır.',
    detailsEn: 'The southern-hemisphere antenna complex and third geographic leg of NASA’s Deep Space Network.',
    sourceUrl: 'https://www.jpl.nasa.gov/missions/dsn/',
  },

  // 🌕 MOON
  {
    id: 'apollo11',
    bodyId: 'moon',
    name: 'Apollo 11 (Mare Tranquillitatis)',
    nameTr: 'Apollo 11 İniş Alanı',
    year: 1969,
    agency: 'NASA (USA)',
    agencyTr: 'NASA (ABD)',
    lat: 0.67,
    lon: 23.47,
    emoji: '🇺🇸',
    detailsTr: 'Neil Armstrong ve Buzz Aldrin\'in insanlık tarihinde Ay yüzeyine ilk ayak bastığı tarihi alan ("İnsan için küçük, insanlık için büyük bir adım").',
    sourceUrl: 'https://www.nasa.gov/missions/apollo/apollo-11/apollo-11-mission-overview/',
  },
  {
    id: 'apollo12',
    bodyId: 'moon',
    name: 'Apollo 12 (Oceanus Procellarum)',
    nameTr: 'Apollo 12 İniş Alanı',
    year: 1969,
    agency: 'NASA (USA)',
    agencyTr: 'NASA (ABD)',
    lat: -3.01,
    lon: -23.42,
    emoji: '🇺🇸',
    detailsTr: 'Pete Conrad ve Alan Bean tarafından Surveyor 3 uzay aracının yakınına hassas iniş yapıldığı görev.',
    sourceUrl: 'https://www.nasa.gov/the-apollo-program/',
  },
  {
    id: 'apollo15',
    bodyId: 'moon',
    name: 'Apollo 15 (Hadley-Apennine)',
    nameTr: 'Apollo 15 İniş Alanı',
    year: 1971,
    agency: 'NASA (USA)',
    agencyTr: 'NASA (ABD)',
    lat: 26.13,
    lon: 3.63,
    emoji: '🇺🇸',
    detailsTr: 'İlk kez Ay Taşıtı (Lunar Roving Vehicle) sürülen ve Genesis taşının bulunduğu görev.',
    sourceUrl: 'https://www.nasa.gov/missions/apollo/apollo-15-mission-details/',
  },
  {
    id: 'apollo17',
    bodyId: 'moon',
    name: 'Apollo 17 (Taurus-Littrow)',
    nameTr: 'Apollo 17 İniş Alanı',
    year: 1972,
    agency: 'NASA (USA)',
    agencyTr: 'NASA (ABD)',
    lat: 20.19,
    lon: 30.77,
    emoji: '🇺🇸',
    detailsTr: 'Eugene Cernan ve jeolog Harrison Schmitt\'in Ay yüzeyinde yürüdüğü son insanlı Apollo görevi.',
    sourceUrl: 'https://www.nasa.gov/the-apollo-program/',
  },
  {
    id: 'change4',
    bodyId: 'moon',
    name: 'Chang\'e 4 (Von Kármán Crater)',
    nameTr: 'Chang\'e 4 (Ay\'ın Uzak Yüzü)',
    year: 2019,
    agency: 'CNSA (China)',
    agencyTr: 'CNSA (Çin)',
    lat: -45.45,
    lon: 177.6,
    emoji: '🇨🇳',
    detailsTr: 'İnsanlık tarihinde Ay\'ın uzak yüzüne yumuşak iniş yapan ilk uzay aracı ve Yutu-2 gezgini.',
    sourceUrl: 'https://www.cnsa.gov.cn/english/n6465652/n6465653/c6805049/content.html',
  },

  // 🔴 MARS
  {
    id: 'perseverance',
    bodyId: 'mars',
    name: 'Perseverance & Ingenuity (Jezero Crater)',
    nameTr: 'Perseverance Gezgini & Ingenuity',
    year: 2021,
    agency: 'NASA (USA)',
    agencyTr: 'NASA (ABD)',
    lat: 18.38,
    lon: 77.58,
    emoji: '🤖',
    detailsTr: 'Eski göl yatağı Jezero Krateri\'nde antik yaşam izleri arayan nükleer enerjili gezgin ve Mars helikopteri Ingenuity.',
    sourceUrl: 'https://science.nasa.gov/mission/mars-2020-perseverance/',
  },
  {
    id: 'curiosity',
    bodyId: 'mars',
    name: 'Curiosity Rover (Gale Crater)',
    nameTr: 'Curiosity Gezgini',
    year: 2012,
    agency: 'NASA (USA)',
    agencyTr: 'NASA (ABD)',
    lat: -4.58,
    lon: 137.44,
    emoji: '🚙',
    detailsTr: 'Gale Krateri ve Sharp Dağı eteklerinde Mars\'ın geçmişte mikrobiyel yaşama elverişli olduğunu kanıtlayan gezgin.',
    sourceUrl: 'https://science.nasa.gov/mission/msl-curiosity/',
  },
  {
    id: 'viking1',
    bodyId: 'mars',
    name: 'Viking 1 Lander (Chryse Planitia)',
    nameTr: 'Viking 1 İniş Aracı',
    year: 1976,
    agency: 'NASA (USA)',
    agencyTr: 'NASA (ABD)',
    lat: 22.48,
    lon: -47.97,
    emoji: '📡',
    detailsTr: 'Mars yüzeyine başarıyla inen ve ilk yüksek çözünürlüklü renkli fotoğrafları Dünya\'ya gönderen tarihi iniş aracı.',
    sourceUrl: 'https://science.nasa.gov/mission/viking-1/',
  },
  {
    id: 'zhurong',
    bodyId: 'mars',
    name: 'Zhurong Rover (Utopia Planitia)',
    nameTr: 'Zhurong Gezgini',
    year: 2021,
    agency: 'CNSA (China)',
    agencyTr: 'CNSA (Çin)',
    lat: 25.06,
    lon: 109.92,
    emoji: '🇨🇳',
    detailsTr: 'Çin\'in Tianwen-1 görevi kapsamında Utopia Planitia düzlüğüne indirdiği ilk Mars gezgini.',
    sourceUrl: 'https://www.cnsa.gov.cn/english/n6465652/n6465653/c6812005/content.html',
  },

  // 🪐 TITAN
  {
    id: 'huygens',
    bodyId: 'titan',
    name: 'Huygens Probe (Adiri Region)',
    nameTr: 'Huygens Sondası',
    year: 2005,
    agency: 'ESA / NASA',
    agencyTr: 'ESA (Avrupa) / NASA',
    lat: -10.2,
    lon: 192.4,
    emoji: '🛰️',
    detailsTr: 'Cassini uzay aracından ayrılarak Satürn\'ün dev uydusu Titan\'ın organik atmosferinden süzülüp inen, dış Güneş Sistemi\'ndeki ilk yüzey aracı.',
    sourceUrl: 'https://www.esa.int/Science_Exploration/Space_Science/Cassini-Huygens/The_mission',
  },

  // 🟡 VENUS
  {
    id: 'venera13',
    bodyId: 'venus',
    name: 'Venera 13 (Phoebe Regio)',
    nameTr: 'Venera 13 Sondası',
    year: 1982,
    agency: 'Soviet Space Program',
    agencyTr: 'Sovyetler Birliği (SSCB)',
    lat: -7.5,
    lon: 303.0,
    emoji: '🔴',
    detailsTr: 'Venüs yüzeyinde ölçtüğü 465°C sıcaklık ve 89,5 atmosfer basınç altında 127 dakika veri iletti; Venüs yüzeyinin ilk renkli fotoğraflarını Dünya\'ya gönderdi.',
    sourceUrl: 'https://www.nasa.gov/wp-content/uploads/2023/04/sp-4524.pdf#page=141',
  },
]

export function findLandingSiteNear(bodyId: string, lat: number, lon: number, radiusThreshold = 15.0): LandingSite | null {
  for (const s of LANDING_SITES) {
    if (s.bodyId === bodyId) {
      const dLat = Math.abs(s.lat - lat)
      const dLon = Math.abs(s.lon - lon)
      if (dLat < radiusThreshold && dLon < radiusThreshold) {
        return s
      }
    }
  }
  return null
}
